### ISSUE TITLE
When an entry is deleted, the favicon does not

### ISSUE THREAD

**Issue by user8446** [navossoc/KeePass-Yet-Another-Favicon-Downloader#13]
I'm not sure if this is a bug or not. When an entry is deleted, the favicon stays in the custom icon database. Over time you database can grow with many unused icons.

**Comment by navossoc** [comment]
Hi @user8446, this is by design.
I am not sure if KeePass let me hook the delete function and remove the icon at the same time. Probably not.

I think that's the reason the KeePass developer added this tool:
`Tools -> Database Tools -> Delete Unused Custom Icons`

It will check all the custom icons and and delete only those icons that are not associated with any entry.

**Comment by user8446** [comment]
Thanks, I didn't know if it was easy to implement to save that step.
Thank you for the development!
