### ISSUE TITLE
Fail to find favicon for opensensemap.org

### ISSUE THREAD

**Issue by domoenergytics** [navossoc/KeePass-Yet-Another-Favicon-Downloader#21]
Hi,

YAFD is failing to find the favicon for https://opensensemap.org. 
I believe it should be finding an icon based on the following tag :
<link rel="icon" href="images/a86afe07.favicon.svg">

**Comment by navossoc** [comment]
I'm planning to finish this update this week:  (busy days!)
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/pull/19

It may solve the issue. I'll look into.

PS: There is no favicon for me on chrome or edge, just on firefox.

**Comment by Nikey646** [comment]
This website appears to use an SVG as an favicon. #19 will not resolve this, and will require additional work (Primarily, converting SVG to an image)

**Comment by Nikey646** [comment]
Just quickly tested the site you linked, and it just returns the .svg itself.

With the fact that a site like that could go down without any warning, it also adds a level of... concern?

**Comment by navossoc** [comment]
As I said, create or use, so probably I will have a main endpoint offering the service for YAFD and maybe an option to choose another compatible endpoint (if we get there).

Also, I think if we have a downtime we can live without downloading a favicon for a few minutes, right?

The best advantage of all will be more compatible with Mono.
Since the job on the client side will be much more simpler.

[]'s

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
