### ISSUE TITLE
Error downloading any icons

### ISSUE THREAD

**Issue by Swash1972** [navossoc/KeePass-Yet-Another-Favicon-Downloader#33]
I would love to give you debug output, but I have not been able to find ANY documentation pointing as to where keepass2 places logs.
I'm running Keepass 2.38 with YAFD v1.2.2.0 on Linux Mint 19.2 x64
Latest mono dev and certificates installed and confirmed.
All https urls are failing. http and https
If you can point me in the direction of logs, I can add that here.

**Comment by navossoc** [comment]
Hi @Swash1972, there is no log...

I'll try check it out until the end of this week.

What mono version are you using?

Meanwhile, a quick test is on the menu: file -> open url.
Check if you can import a database from a website (http and/or https).

If that feature is not working, probably the problem is with mono runtime.

[]'s

**Comment by Swash1972** [comment]
Thanks for the reply!
Checked mono version and I was running Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
I noticed that this requires Mono 4.8.0 or newer.
Upgraded mono to Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:21:28 UTC 2019)
All is well and I'm updating favicons just fine!
Thanks for the input!

**Comment by navossoc** [comment]
Yeah, sorry about that...
Mono 4.6 has a few issues, we had a few issues here on github related to this version.
